from typing import Any


class Upbit:
    def __init__(self, access: str, secret: str) -> None: ...
    def get_balance(self, currency: str = "KRW") -> Any: ...
    def get_balances(self) -> Any: ...
    def get_order(self, uuid: str) -> Any: ...
    def get_chance(self, ticker: str) -> Any: ...
    def cancel_order(self, uuid: str) -> Any: ...
    def buy_market_order(self, ticker: str, price: float) -> Any: ...
    def sell_market_order(self, ticker: str, volume: float) -> Any: ...


def get_ohlcv(ticker: str, interval: str = "day", count: int = 200, *args: Any, **kwargs: Any) -> Any: ...
def get_current_price(ticker: Any, *args: Any, **kwargs: Any) -> Any: ...

